PKG_CHECK_MODULES(GLIB "glib-2.0>=2.0")
PKG_CHECK_MODULES(PANGO "pango>=1.0")
PKG_CHECK_MODULES(GTK3 "gtk+-3.0>=3.22" "gdk-pixbuf-2.0")
FIND_PATH(GTK3_INCLUDE_DIRS NAMES gtk/gtk.h
    HINTS ${PC_GTK3_INCLUDE_DIRS} ${PC_GTK3_INCLUDEDIR} ${PC_PANGO_INCLUDEDIR} ${PC_GLIB_INCLUDEDIR}
)

FIND_LIBRARY(GTK3_LIBRARIES NAMES gtk-3.0
    HINTS ${PC_GTK3_LIBRARY_DIRS} ${PC_GTK3_LIBDIR} ${PC_PANGO_LIBDIR} ${PC_GLIB_LIBDIR}
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GTK3 DEFAULT_MSG GTK3_INCLUDE_DIRS GTK3_LIBRARIES)
