PKG_CHECK_MODULES(SDL2 "sdl2")
FIND_PATH(SDL2_INCLUDE_DIRS NAMES SDL2/SDL.h
    HINTS ${PC_SDL2_INCLUDE_DIRS} ${PC_SDL2_INCLUDEDIR} ${PC_PANGO_INCLUDEDIR} ${PC_GLIB_INCLUDEDIR}
)

FIND_LIBRARY(SDL2_LIBRARIES NAMES SDL2
    HINTS ${PC_SDL2_LIBRARY_DIRS} ${PC_SDL2_LIBDIR} ${PC_PANGO_LIBDIR} ${PC_GLIB_LIBDIR}
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2 DEFAULT_MSG SDL2_INCLUDE_DIRS SDL2_LIBRARIES)
