PKG_CHECK_MODULES(PC_LOG4CPP log4cpp>=1.1)
FIND_PATH(LOG4CPP_INCLUDE_DIRS NAMES log4cpp/Category.hh
    HINTS ${PC_LOG4CPP_INCLUDE_DIRS} ${PC_LOG4CPP_INCLUDEDIR}
)

FIND_LIBRARY(LOG4CPP_LIBRARIES NAMES log4cpp
    HINTS ${PC_LOG4CPP_LIBRARY_DIRS} ${PC_LOG4CPP_LIBDIR}
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LOG4CPP DEFAULT_MSG LOG4CPP_INCLUDE_DIRS LOG4CPP_LIBRARIES)
